### ISSUE TITLE
Forgot to commit build.fsx

### ISSUE THREAD

**Issue by ronnieholm** [bengobeil/StonkWatch#1]
It's a solution file, but not in file system.

**Comment by bengobeil** [comment]
There is no build.fsx. Use `dotnet tool restore` and `dotnet run` at the root to run the Build.fsproj. This is a new way of using FAKE.

**Comment by ronnieholm** [comment]
I'm aware of Fake. My point was you added build.fsx to the project but it isn't in the file system. See the file missing indicator in VS.
